### ISSUE TITLE
New columns don't appear when added to `useDataTableColumns`

### ISSUE THREAD

**Issue by techied** [icflorescu/mantine-datatable#596] opened 2024-05-17 22:56 UTC
**Describe the bug**
When using the `useDataTableColumns` hook (as described in the [Column Toggling Example](https://icflorescu.github.io/mantine-datatable/examples/column-dragging-and-toggling/#column-toggling)), new columns added to the `columns` prop do not appear (in the table or in `effectiveColumns`) until `resetColumnsOrder` is called (or the local storage key `${key}-columns-order` is cleared)

**To Reproduce**

1. Copy the Column Toggling Example
2. Load the page
3. Add a column to the columns prop (one which has not been used before)
4. Observe that the new column does not appear

**Expected behavior**
The column should appear

**Screenshots**
Happy to provide a screen recording if helpful in reproducing the issue

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 124

**Comment by nicobermudez** [comment] 2024-06-11 09:18
Bump. I'm running into this same issue

**Comment by icflorescu** [comment] 2024-06-15 10:18
Thanks for raising the issue.
Due to some family issues I won't have any spare time over the next week, so I'd be more than grateful if anyone else is willing to take a look at this. @gfazioli, maybe? :-)

**Comment by gfazioli** [comment] 2024-06-15 14:23
@nicobermudez Thank you for reporting. I'll try to replicate that and investigate

**Comment by devkoller** [comment] 2024-06-18 04:34
I have same issue!

wating for @gfazioli pull request will merge to update mantine datatable.

**Comment by gfazioli** [comment] 2024-06-18 06:46
> I have same issue!
> 
> wating for @gfazioli pull request will merge to update mantine datatable.

PR ready, waiting for @icflorescu approval/merge/release

**Comment by icflorescu** [comment] 2024-06-18 07:50
Thanks a lot for taking the time, @gfazioli, you're a star!
This will do for now; I'm not yet able to get back to work, but everything seems to be working, so the fix went into `7.10.3`.

**Comment by techied** [comment] 2024-06-18 17:02
Thank you @gfazioli !

**Comment by nicobermudez** [comment] 2024-06-18 17:16
Thank you for the work on this! Will really help us next few weeks 👍

**Comment by icflorescu** [comment] 2024-06-24 18:20
Sorry everyone, this issue is now reopened due to a different regression introduced by the fix.
Due to a personal issue - my mother recovering in the hospital after a stroke, I haven't slept properly for more than a week and I simply don't have any mental energy and resources left at the moment.

Hopefully @gfazioli or someone else will be able to come up with a new solution soon. 

For the benefit of the project/community, I'd be more than grateful for any help maintaining this project over the next couple of weeks 😫🙏

**Comment by mikkurogue** [comment] 2024-06-26 11:48
If I have time, I can also take a look at the issue if @gfazioli or @icflorescu do not have the time.

**Comment by gfazioli** [comment] 2024-06-26 13:04
> If I have time, I can also take a look at the issue if @gfazioli or @icflorescu do not have the time.

you  mean https://github.com/icflorescu/mantine-datatable/issues/605?

**Comment by icflorescu** [comment] 2024-06-30 14:33
Thanks again, @gfazioli! Your PR was released in `7.11.0`. The code in [`useDataTableColumns.ts`](https://github.com/icflorescu/mantine-datatable/blob/main/package/hooks/useDataTableColumns.ts) definitely needs some cleanup; it would be nice if you, @mikkurogue, could also take a look at it when you have some spare time.

Please make your PRs against the `next` branch.

Thank you all!

I'll close thisfor now, please feel free to reopen and come up with PRs if necessary.

**Closed by icflorescu** 2024-06-30 14:33 UTC
Labels: help wanted

**Comment by mikkurogue** [comment] 2024-07-03 12:28
@icflorescu 
On first glance, after reading useDataTableColumns.ts, I can't necessarily see much "wrong" other than potential performance increases from the runtime but I'm doubtful this would provide much value in the grand scheme of things. I can still provide a PR later if you feel like looking over it
