### ISSUE TITLE
Datatable creating issue with mantine core

### ISSUE THREAD

**Issue by Osako21** [icflorescu/mantine-datatable#423] opened 2023-09-22 15:50 UTC
**Describe the bug**
After installing datatable to my working mantine vite  react project I am getting this error multiple times on server start

`
✘ [ERROR] No matching export in "node_modules/@mantine/core/esm/index.js" for import "createStyles"

    node_modules/mantine-datatable/dist/index.mjs:1:25234:
      1 │ ...size:"sm",children:e})]})}a();import{Box as Tr,createStyles as Sf,ScrollArea as bf}from"@mantine/core";im...
        ╵`

**To Reproduce**

1. Create a react vite project
2. install mantine UI
3. install mantine datatable
4. start server

**Expected behavior**
Server should start
**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/77686244/0f12d544-2ea5-4ef6-846f-24f9d05a8ddd)
**Desktop (please complete the following information):**

- OS: IOS ventura 13.5.2
- Browser Chrome
- Version  116.0.5845.110

**Comment by ericschmar** [comment] 2023-09-22 18:17
This is a duplicate of #420

**Comment by icflorescu** [comment] 2023-10-31 19:38
The alpha version of V7.1 is [finally here](https://icflorescu.github.io/mantine-datatable/):

[![Mantine DataTable V7](https://github.com/icflorescu/mantine-datatable/assets/581999/0be62c66-978e-4ecc-9abe-0dad3254c94d)](https://icflorescu.github.io/mantine-datatable/)

See https://github.com/icflorescu/mantine-datatable/issues/420#issuecomment-1787913513 for a full status update.

**Closed by icflorescu** 2023-10-31 19:38 UTC
Labels: duplicate
