### ISSUE TITLE
When I give empty data, an empty row appears

### ISSUE THREAD

**Issue by arifsygl** [icflorescu/mantine-datatable#138] opened 2022-11-30 15:06 UTC
**Describe the bug**
When I give empty data, an empty row appears

**Screenshots**
<img width="453" alt="Screen Shot 2022-11-30 at 17 58 14" src="https://user-images.githubusercontent.com/104317611/204833424-aa173b1b-27fd-4c0a-b2bd-5c179ecd9da6.png">

<img width="729" alt="Screen Shot 2022-11-30 at 17 58 54" src="https://user-images.githubusercontent.com/104317611/204832692-1b93cbc1-9598-4156-8915-85cc41479f18.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOs]
 - Browser [chrome]

Thanks for helps.

**Comment by icflorescu** [comment] 2022-11-30 17:03
I'm sorry, but I am unable to reproduce.

Try setting a `minHeight` and see if the problem persists.
Have a look at the empty-state docs/examples: https://icflorescu.github.io/mantine-datatable/examples/empty-state

If you still think there's a problem, please provide a working example (on codesandbox or something like that)...

**Comment by arifsygl** [comment] 2022-11-30 20:36
I am sharing the codesandbox link below. When you inspect the table, you will see an empty row and an empty column appear.

I noticed that when I use Tailwind, it gives a border to the empty column, so I'm having such a problem.

https://codesandbox.io/s/elated-mayer-rbu7h1?file=/src/index.js

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/104317611/204902737-76042f0c-fd73-4f7a-a693-aaf0c518aa11.png">

**Comment by arifsygl** [comment] 2022-12-01 10:50
@icflorescu Thank you for your fast response!

**Comment by aaly00** [comment] 2022-12-02 19:35
facing same problem

**Comment by aaly00** [comment] 2022-12-02 19:36
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/11652379/205372037-40ae92f1-0754-4953-a05d-ca7f2e0dc2d7.png">

**Comment by aaly00** [comment] 2022-12-02 20:24
I created a working stackblitz demonstrating the issue https://stackblitz.com/edit/nextjs-b4kcz9?file=pages/index.js

**Comment by icflorescu** [comment] 2022-12-02 23:20
Thanks for the stackblitz.
Fixed in `v1.7.22`.

**Closed by icflorescu** 2022-12-02 23:20 UTC
Labels: invalid, needs more info
