### ISSUE TITLE
empty datatable table tbody tr table 1 row added

### ISSUE THREAD

**Issue by maungyehtunzaw** [icflorescu/mantine-datatable#409] opened 2023-08-16 03:26 UTC
![image](https://github.com/icflorescu/mantine-datatable/assets/5591177/1a966634-f8ce-4529-abc4-300fedb96ae0)

```
  <DataTable
            minHeight={150}
              columns={[
                {
                    accessor: "id",
                },
                {
                    accessor: "code",

                },
                {
                    accessor: "name",

                },
                {
                    accessor: "name_my",

                },
                {
                    accessor: "group_class",

                },]}
                records={[]}

            />
```

**Comment by maungyehtunzaw** [comment] 2023-08-25 04:53
> ![image](https://user-images.githubusercontent.com/5591177/260892517-1a966634-f8ce-4529-abc4-300fedb96ae0.png)
> 
> ```
>   <DataTable
>             minHeight={150}
>               columns={[
>                 {
>                     accessor: "id",
>                 },
>                 {
>                     accessor: "code",
> 
>                 },
>                 {
>                     accessor: "name",
> 
>                 },
>                 {
>                     accessor: "name_my",
> 
>                 },
>                 {
>                     accessor: "group_class",
> 
>                 },]}
>                 records={[]}
> 
>             />
> ```

**Comment by icflorescu** [comment] 2023-08-29 12:13
The `tbody` does indeed have an empty row when noe records are provided, but this behaviour is intentional (to keep the layout consistent, as far as I remember) and the empty row is styled to be invisible, as you can see in the documentation website here: https://icflorescu.github.io/mantine-datatable/examples/empty-state

Did you override the styles?
Can you please share a reproduction on codesandbox or something similar?

**Comment by icflorescu** [comment] 2023-09-04 12:16
I'm going to close this, since it doesn't appear on the docs website nor in other usage scenarios.
Please feel free to reopen if you can come up with a valid reporoduction.
Thanks!

**Closed by icflorescu** 2023-09-04 12:16 UTC
Labels: invalid, needs more info

**Comment by nkelton** [comment] 2024-03-23 03:55
Hello @icflorescu! I was able to reproduce this issue with the following DataTable: 
```jsx
        <DataTable
          height={360}
          striped
          border={1}
          borderColor={'var(--mantine-color-dark-4)'}
          withColumnBorders
          highlightOnHover
          fetching={isLoading}
          onScrollToBottom={handleOnScrollToBottom}
          scrollViewportRef={viewport}
          records={data?.pages.flat() || []}
          columns={
            [
              /*omitted*/
            ]
          }
          onRowClick={handleRowClick}
          defaultColumnProps={{
            titleStyle: () => ({ color: 'var(--mantine-color-indigo-text)' })
          }}
          highlightOnHoverColor={'var(--mantine-color-indigo-light)'}
          emptyState={
            <Box p={4} mb={4}>
              <NoRecordsIcon size={36} />
            </Box>
          }
        />
```
