### ISSUE TITLE
Make row actions cell sticky

### ISSUE THREAD

**Issue by KaptinLin** [icflorescu/mantine-datatable#96] opened 2022-10-17 03:43 UTC
**Is your feature request related to a problem? Please describe.**
Make row actions cell sticky like the first checkbox cell.

![image](https://user-images.githubusercontent.com/999331/196084505-b20304d6-041a-4f7b-8d61-0984d63b7101.png)

**Describe the solution you'd like**
Add sticky property to column properties

```
        accessor: 'actions',
        title: <Text mr="xs">Row actions</Text>,
        textAlignment: 'right',
        sticky: true,
```

**Comment by icflorescu** [comment] 2022-10-28 21:36
Duplicate of #78

**Comment by otobot1** [comment] 2022-11-16 18:48
Should this be closed? It was marked as a duplicate.

**Closed** 2023-01-03 01:22 UTC
Labels: duplicate
