### ISSUE TITLE
Debounce error

### ISSUE THREAD

**Issue by FerLeiva** [icflorescu/mantine-datatable#147] opened 2022-12-09 01:18 UTC
I have an Error when using the package with nextjs in Chrome, even if i only copy the example and more basic code.

![image](https://user-images.githubusercontent.com/66581357/206601045-7f5cc2cd-3d34-4eaa-bbb4-ea329e56bed3.png)

It never renders, I dont know whats happening

**Comment by icflorescu** [comment] 2022-12-09 07:36
Can you please provide a stackblitz or codesandbox example reproducing the bug?
I think most people are using it with Next.js; even [the docs website](https://icflorescu.github.io/mantine-datatable) is built with Next.js, so there should be no such issue...

**Comment by icflorescu** [comment] 2022-12-12 13:17
Due to the lack of follow up, I'm going to assume the issue is not related to Mantine DataTable per se and close it.
Feel free to reopen if you can provide a reproduction.

**Closed by icflorescu** 2022-12-12 13:17 UTC
Labels: invalid, needs more info
