### ISSUE TITLE
Row highlighting isn't working

### ISSUE THREAD

**Issue by reubenfirmin** [icflorescu/mantine-datatable#375] opened 2023-07-16 16:37 UTC
**Describe the bug**
In your own example, highlightOnHover doesn't work: https://icflorescu.github.io/mantine-datatable/examples/basic-table-properties

I have the same issue in my own code.

**Comment by icflorescu** [comment] 2023-07-17 17:09
Hey, @reubenfirmin, what do you mean `highlightOnHover` doesn't work?

I just had a look at it again and it looks to me like it's working on all possible environments I could test it on: Chrome, Firefox, Edge on both Linux and Windows, Safari on macOS.

![2023-07-17 19-55-32](https://github.com/icflorescu/mantine-datatable/assets/581999/f92cdfff-46b3-44d4-83cf-c6cd06680a67)


Maybe I'm missing something?!

**Comment by icflorescu** [comment] 2023-07-18 12:49
Any feedback on this, @reubenfirmin?

**Comment by icflorescu** [comment] 2023-07-20 11:17
I'm going to close this for now, since I can't reproduce it.
Feel free to reopen if you can come up with feedback including a valid reproduction.

Thanks!

**Closed by icflorescu** 2023-07-20 11:17 UTC
Labels: needs more info
